# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x03rpc\"P\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x0b\n\x03tag\x18\x05 \x01(\t\"\x14\n\x06TaskID\x12\n\n\x02id\x18\x01 \x01(\x03\"7\n\x0cTaskResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x17\n\x04task\x18\x02 \x01(\x0b\x32\t.rpc.Task\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\":\n\x10PaginationParams\x12\x13\n\x0bpage_number\x18\x01 \x01(\t\x12\x11\n\tpage_size\x18\x02 \x01(\t\"4\n\x08TaskList\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x18\n\x05tasks\x18\x02 \x03(\x0b\x32\t.rpc.Task2\xf6\x01\n\x0bTaskService\x12*\n\nCreateTask\x12\t.rpc.Task\x1a\x11.rpc.TaskResponse\x12*\n\nUpdateTask\x12\t.rpc.Task\x1a\x11.rpc.TaskResponse\x12.\n\nDeleteTask\x12\x0b.rpc.TaskID\x1a\x13.rpc.DeleteResponse\x12-\n\x0bGetTaskByID\x12\x0b.rpc.TaskID\x1a\x11.rpc.TaskResponse\x12\x30\n\x08GetTasks\x12\x15.rpc.PaginationParams\x1a\r.rpc.TaskListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TASK']._serialized_start=22
  _globals['_TASK']._serialized_end=102
  _globals['_TASKID']._serialized_start=104
  _globals['_TASKID']._serialized_end=124
  _globals['_TASKRESPONSE']._serialized_start=126
  _globals['_TASKRESPONSE']._serialized_end=181
  _globals['_DELETERESPONSE']._serialized_start=183
  _globals['_DELETERESPONSE']._serialized_end=216
  _globals['_PAGINATIONPARAMS']._serialized_start=218
  _globals['_PAGINATIONPARAMS']._serialized_end=276
  _globals['_TASKLIST']._serialized_start=278
  _globals['_TASKLIST']._serialized_end=330
  _globals['_TASKSERVICE']._serialized_start=333
  _globals['_TASKSERVICE']._serialized_end=579
# @@protoc_insertion_point(module_scope)
