version: '3'

services:
  authentication_service:
    build:
      context: ./services
      dockerfile: authentication_service.Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - task_service
      - database_service
      - kafka
    volumes:
      - db_data:/data

  task_service:
    build:
      context: ./services
      dockerfile: task_service.Dockerfile
    ports:
      - "51075:51075"
    depends_on:
      - database_service
    volumes:
      - db_data:/data

  statistics_service:
    build:
      context: ./services
      dockerfile: statistics_service.Dockerfile
    ports:
      - "51076:51076"
    depends_on:
      - database_service
      - kafka
    volumes:
      - db_data:/data

  database_service:
    build: services/database_service
    volumes:
      - db_data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

volumes:
  db_data:
