version: '3'

services:
  authentication_service:
    build: ./authentication_service
    ports:
      - "5001:5000"
    depends_on:
      - database_service
    volumes:
      - db_data:/data

  database_service:
    build: ./database_service
    volumes:
      - db_data:/data

volumes:
  db_data:
