version: '3'

services:
  authentication_service:
    build: ./authentication_service
    ports:
      - "5000:5000"
    depends_on:
      - database_service

  database_service:
    build: ./database_service
    ports:
      - "5432:5432"
