openapi: 3.0.0
info:
  title: User Service API
  version: 1.0.0
  description: SOA Nasheverdov project

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                firstName:
                  type: string
                lastName:
                  type: string
                dob:
                  type: string
                  format: date
                email:
                  type: string
                  format: email
                phoneNumber:
                  type: string
      responses:
        '201':
          description: User successfully registered
        '400':
          description: Bad request, check input data

  /update:
    put:
      summary: Update user data
      security:
        - BasicAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                dob:
                  type: string
                  format: date
                email:
                  type: string
                  format: email
                phoneNumber:
                  type: string
      responses:
        '200':
          description: User data updated
        '400':
          description: Bad request, check input data
        '401':
          description: Unauthorized, check login credentials

  /auth:
    post:
      summary: Authenticate user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User successfully authenticated
        '401':
          description: Unauthorized, check login credentials
